### ISSUE TITLE
Exiting game results in relaunch of same game

### ISSUE THREAD

**Issue by DSX-FX** [mickelson/attract#266]
Multiple users from the RetroPie group on fb are reporting an issue where exiting a game results in the game closing and immediately re-launching.  Does not happen in emulationstation, only attract mode. Doesn't matter which emulator or system you are in, or what type of controller. Exiting with an arcade stick or a wireless keyboard will generate the same issue on the same system. Any ideas of what is causing this problem and what a potential fix might be?

**Comment by JDias** [comment]
Is attract mode now part of retropie?

**Comment by DSX-FX** [comment]
You can install it and switch between emulation station or attract mode. It will let you default to either one.

**Comment by DSX-FX** [comment]
After testing various devices, seems to only happen while using keyboard or keyboard based controller boards.  Wireless keyboard, wired keyboard, and picade pcb all produce the bug using (c+s) to exit a game.  Using a Logitech F310, I have not been able to produce the bug at all, not once.  Not sure why this is happening as coding is not my strength...

**Comment by csavvas** [comment]
I have the same issue. It seems like that it remembers the keys pressed in game and when exiting is pressing all those keys again.

**Comment by mickelson** [comment]
In the configuration menu you can change the "Window Mode" setting (General->Window Mode)

Does switching Window Mode to "Fill Screen" or "Fullscreen Mode" affect whether this happens?

**Comment by bakazm** [comment]
I was having the same issue (pi3, keyboard inputs, AM 2.1) - looks like keypresses are being cached and passed onto attract mode when MAME exits. I tried switching to Fill Screen and Fullscreen, but they did not solve the problem.

**Comment by leakyscab** [comment]
I'm having same problem.  Has anyone come across a solution?  At first it was only a mild frustration however recently the "cached" keystrokes entered settings menus and made a real mess of things that I have yet to resolve.

**Comment by bakazm** [comment]
This problem does not occur on Floob's v.2 image, which still relied on the X environment. It looks like the newer versions that don't require X have the extra keystroke problem. For now I'm running v.2 until it gets sorted out.

**Comment by mickelson** [comment]
OK this bug should be fixed now with the most recent commit. Confirmation whether it fixes the issue for you would be appreciated. thanks!

**Comment by DSX-FX** [comment]
I will try it out tomorrow and let you know! Thanks!

**Comment by DSX-FX** [comment]
It appears to have solved the issue.  The only thing I noticed was that sometimes when exiting a game, it would jump over to a different system's display or a different game wheel when no directional buttons had been pushed, only the exit combo (start+select).  Definitely an improvement though!  Thanks for looking into it!

**Comment by bakazm** [comment]
The issue is much better, but I still get an occasional "Exit Attract Mode?" prompt when I exit a game. My exit key for MAME is ESC, the same key as Attract Mode. So if anything, only one key press is being cached / repeated.

I also have a new, separate issue where I am unable to type any text in the Attract Mode settings screens, but the up/down/select keys work. This is likely a completely separate issue...

**Comment by cyborgcnc** [comment]
Hi....I am still having this issue, on version 2.2.1 (just did a new install from the github sources).  I am running on a pi 3 with latest build of retropi, but had the same issue on previous 2 retropi versions....Once I exit a mame game, it remembers my escape and enter keypresses, sometimes causing the next rom, or the same run to run again....
I am using an IPAC controller, but I have the same issue with a plain vanilla USB keyboard....Also, changing the window modes, does not have any effect on the issue.....

Any ideas?

**Comment by mickelson** [comment]
the problem was in "sfml-pi".  make sure you have the latest version of that built and installed

https://github.com/mickelson/attract/wiki/Compiling-on-the-Raspberry-Pi-%28Raspbian-Jessie%29

**Comment by cyborgcnc** [comment]
BINGO!!  problem solved.....running all the latest versions, and this did
it!  The keyboard and now even the scrolling on the wheel are SO much
better!  No more issues with exiting the emulator.....

Andrew, thank you so much for your effort and work on this front end.  Do
you have a paypal donation setup?  Would like the info please....

Thanks again,

Spiro

**Comment by M4rc3lv** [comment]
Thanks for this Andrew. I have been working for months on a physical  arcade cabinet using attract-mode and after playing some games I just found out that it worked bad because of this keyboard buffer problem. Your well documented solution worked perfectly. Thanks again!
