### ISSUE TITLE
Jessie upgrades and installs fail (not using RetroPie install menu)

### ISSUE THREAD

**Issue by progets** [mickelson/attract#385]
There are compile issues with changes made in the code in the past month for Pi users. I know this has been fixed for RetroPie Setup users but what about the rest of us? 

Please review this thread http://forum.attractmode.org/index.php?topic=1978.0

Thanks

**Comment by mickelson** [comment]
hi, could you post the output you are getting from make?

**Comment by progets** [comment]
Here's what I see when I try to compile AM after compiling ffmpeg.

`pi@retropie:~/develop/attract $ make USE_GLES=1
flags: -Wl,--export-dynamic -I/usr/include/freetype2  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -I/opt/vc/include -L/opt/vc/lib -Iextlibs/miniz -Iextlibs/udio/include -D__STDC_CONSTANT_MACROS -I/usr/local/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gamswf  -DUSE_GLES -DUSE_FONTCONFIG -DUSE_SWRESAMPLE
mkdir -p obj
Compiling obj/fe_base.o...
In file included from /usr/include/c++/4.9/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/image.h:14,
                 from extlibs/gameswf/gameswf/gameswf.h:21,
                 from src/fe_base.cpp:34:
/usr/include/c++/4.9/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without frther notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consul the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/fe_util.o...
Compiling obj/fe_util_sq.o...
Compiling obj/fe_cmdline.o...
Compiling obj/fe_info.o...
Compiling obj/fe_input.o...
Compiling obj/fe_romlist.o...
Compiling obj/fe_settings.o...
Compiling obj/scraper_xml.o...
Compiling obj/scraper_general.o...
Compiling obj/scraper_net.o...
Compiling obj/fe_config.o...
Compiling obj/fe_presentable.o...
Compiling obj/fe_present.o...
Compiling obj/sprite.o...
Compiling obj/fe_image.o...
Compiling obj/fe_sound.o...
Compiling obj/fe_shader.o...
src/fe_shader.cpp: In member function ‘void FeShader::set_param(const char*, float)’:
src/fe_shader.cpp:84:34: warning: ‘void sf::Shader::setParameter(const string&, float)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Shader.hpp:554) [-Weprecated-declarations]
   m_shader.setParameter( name, x );
                                  ^
src/fe_shader.cpp: In member function ‘void FeShader::set_param(const char*, float, float)’:
src/fe_shader.cpp:93:37: warning: ‘void sf::Shader::setParameter(const string&, float, float)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Shader.hpp:52) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y );
                                     ^
src/fe_shader.cpp: In member function ‘void FeShader::set_param(const char*, float, float, float)’:
src/fe_shader.cpp:102:40: warning: ‘void sf::Shader::setParameter(const string&, float, float, float)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Shadr.hpp:570) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z );
                                        ^
src/fe_shader.cpp: In member function ‘void FeShader::set_param(const char*, float, float, float, float)’:
src/fe_shader.cpp:111:43: warning: ‘void sf::Shader::setParameter(const string&, float, float, float, float)’ is deprecated (declared at /usr/local/include/SFML/Graphis/Shader.hpp:578) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z, w );
                                           ^
src/fe_shader.cpp: In member function ‘void FeShader::set_texture_param(const char*)’:
src/fe_shader.cpp:120:59: warning: ‘void sf::Shader::setParameter(const string&, sf::Shader::CurrentTextureType)’ is deprecated (declared at /usr/local/include/SFML/Grphics/Shader.hpp:626) [-Wdeprecated-declarations]
   m_shader.setParameter( name, sf::Shader::CurrentTexture );
                                                           ^
src/fe_shader.cpp: In member function ‘void FeShader::set_texture_param(const char*, FeImage*)’:
src/fe_shader.cpp:133:42: warning: ‘void sf::Shader::setParameter(const string&, const sf::Texture&)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Shade.hpp:618) [-Wdeprecated-declarations]
    m_shader.setParameter( name, *texture );
                                          ^
Compiling obj/fe_overlay.o...
src/fe_overlay.cpp: In member function ‘bool FeOverlay::edit_loop(std::vector<sf::Drawable*>, std::basic_string<unsigned int>&, FeTextPrimative*)’:
src/fe_overlay.cpp:1575:34: warning: ‘void sf::Text::setColor(const sf::Color&)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Text.hpp:177) [-Wdeprecate-declarations]
  cursor.setColor( tp->getColor() );
                                  ^
Compiling obj/fe_window.o...
Compiling obj/tp.o...
src/tp.cpp: In member function ‘void FeTextPrimative::setColor(const sf::Color&)’:
src/tp.cpp:71:26: warning: ‘void sf::Text::setColor(const sf::Color&)’ is deprecated (declared at /usr/local/include/SFML/Graphics/Text.hpp:177) [-Wdeprecated-declaratons]
   m_texts[i].setColor( c );
                          ^
src/tp.cpp: In member function ‘const sf::Color& FeTextPrimative::getColor() const’:
src/tp.cpp:76:29: warning: ‘const sf::Color& sf::Text::getColor() const’ is deprecated (declared at /usr/local/include/SFML/Graphics/Text.hpp:285) [-Wdeprecated-declartions]
  return m_texts[0].getColor();
                             ^
Compiling obj/fe_text.o...
Compiling obj/fe_listbox.o...
Compiling obj/fe_vm.o...
Compiling obj/zip.o...
Compiling obj/main.o...
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:561:44: warning: ‘sf::Image sf::RenderWindow::capture() const’ is deprecated (declared at /usr/local/include/SFML/Graphics/RenderWindow.hpp:158) [-Wdeprected-declarations]
       sf::Image sshot_img = window.capture();
                                            ^
Compiling obj/fe_net.o...
Compiling obj/swf.o...
In file included from /usr/include/c++/4.9/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/tu_file.h:18,
                 from src/swf.cpp:26:
/usr/include/c++/4.9/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without frther notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consul the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/media.o...
src/media.cpp: In member function ‘void FeVideoImp::preload()’:
src/media.cpp:526:15: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^
src/media.cpp:526:15: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations]
src/media.cpp:531:14: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/acodec.h:4562) [-Wdeprecated-declarations]
    int len = avcodec_decode_video2( codec_ctx, raw_frame,
              ^
src/media.cpp:532:24: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/acodec.h:4562) [-Wdeprecated-declarations]
     &got_frame, packet );
                        ^
src/media.cpp: In member function ‘void FeVideoImp::video_thread()’:
src/media.cpp:698:17: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^
src/media.cpp:698:17: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations]
src/media.cpp:703:16: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/acodec.h:4562) [-Wdeprecated-declarations]
      int len = avcodec_decode_video2( codec_ctx, raw_frame,
                ^
src/media.cpp:704:27: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/acodec.h:4562) [-Wdeprecated-declarations]
        &got_frame, packet );
                           ^
src/media.cpp:710:35: warning: ‘AVFrame::pkt_pts’ is deprecated (declared at /usr/local/include/libavutil/frame.h:302) [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^
src/media.cpp:710:35: warning: ‘AVFrame::pkt_pts’ is deprecated (declared at /usr/local/include/libavutil/frame.h:302) [-Wdeprecated-declarations]
src/media.cpp: In member function ‘bool FeMedia::openFromArchive(const string&, const string&, sf::Texture*)’:
src/media.cpp:973:6: error: ‘FF_INPUT_BUFFER_PADDING_SIZE’ was not declared in this scope
    + FF_INPUT_BUFFER_PADDING_SIZE );
      ^
src/media.cpp: In member function ‘bool FeMedia::internal_open(sf::Texture*)’:
src/media.cpp:1012:73: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
src/media.cpp:1012:73: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Wdeprecated-declarations]
src/media.cpp:1033:8: error: ‘FF_INPUT_BUFFER_PADDING_SIZE’ was not declared in this scope
      + FF_INPUT_BUFFER_PADDING_SIZE
        ^
src/media.cpp:1067:73: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
src/media.cpp:1067:73: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Wdeprecated-declarations]
src/media.cpp: In member function ‘virtual bool FeMedia::onGetData(sf::SoundStream::Chunk&)’:
src/media.cpp:1224:23: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^
src/media.cpp:1224:23: warning: ‘AVCodecContext::refcounted_frames’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2307) [-Wdeprecated-declarations
src/media.cpp:1233:13: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/vcodec.h:4513) [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packet );
             ^
src/media.cpp:1233:82: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /usr/local/include/libavcodec/vcodec.h:4513) [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packet );
                                                                                  ^
Makefile:438: recipe for target 'obj/media.o' failed
make: *** [obj/media.o] Error 1
`

**Comment by mickelson** [comment]
Ok I think this should be fixed now.  Please pull the latest attractmode code from github and try compiling again.  Thanks

**Comment by progets** [comment]
Thanks for your quick response. AM now compiles but doesn't run. I have this problem if I manually compile ffmpeg or if I use the prebuilt AV modules. I noticed that most of the files normally in .attract folder were missing so I manually copied them over from another build but this didn't help. This is a fresh build using the image from directly from RetroPie (not somebody's hack job). It's fully updated and I can install and run AM if I use the RetroPie Setup menu to install AM but this doesn't give me the same flexibility.

Here's the output when I try to run AM.

pi@retropie:~ $ attract
Attract-Mode v2.3.0 (Linux, SFML 2.4 +FontConfig +GLES +SWF)
avcodec 58.3.105 / avformat 58.2.102 / swscale 5.0.101 / swresample 3.0.101

Config file not found: /home/pi/.attract/attract.cfg, performing initial setup.
Copying: '/usr/local/share/attract/emulators/mess-a7800.cfg' to '/home/pi/.attra                                                                                        ct/emulators/'
Copying: '/usr/local/share/attract/emulators/gens.cfg' to '/home/pi/.attract/emu                                                                                        lators/'
Copying: '/usr/local/share/attract/emulators/windows_games.cfg' to '/home/pi/.at                                                                                        tract/emulators/'
Copying: '/usr/local/share/attract/emulators/mame.cfg' to '/home/pi/.attract/emu                                                                                        lators/'
Copying: '/usr/local/share/attract/emulators/steam.cfg' to '/home/pi/.attract/em                                                                                        ulators/'
Copying: '/usr/local/share/attract/emulators/Dolphin.cfg' to '/home/pi/.attract/                                                                                        emulators/'
Copying: '/usr/local/share/attract/emulators/scumm-vm.cfg' to '/home/pi/.attract                                                                                        /emulators/'
Copying: '/usr/local/share/attract/emulators/mess-genesis.cfg' to '/home/pi/.att                                                                                        ract/emulators/'
Copying: '/usr/local/share/attract/emulators/zsnes.cfg' to '/home/pi/.attract/em                                                                                        ulators/'
Copying: '/usr/local/share/attract/emulators/video.cfg' to '/home/pi/.attract/em                                                                                        ulators/'
Copying: '/usr/local/share/attract/emulators/daphne.cfg' to '/home/pi/.attract/e                                                                                        mulators/'
Copying: '/usr/local/share/attract/emulators/vice.cfg' to '/home/pi/.attract/emu                                                                                        lators/'
Copying: '/usr/local/share/attract/emulators/mess-neocdz.cfg' to '/home/pi/.attr                                                                                        act/emulators/'
Copying: '/usr/local/share/attract/emulators/fusion.cfg' to '/home/pi/.attract/e                                                                                        mulators/'
Copying: '/usr/local/share/attract/emulators/mess-snes.cfg' to '/home/pi/.attrac                                                                                        t/emulators/'
Copying: '/usr/local/share/attract/emulators/mednafen.cfg' to '/home/pi/.attract                                                                                        /emulators/'
Copying: '/usr/local/share/attract/emulators/nestopia.cfg' to '/home/pi/.attract                                                                                        /emulators/'
Copying: '/usr/local/share/attract/emulators/pcsx.cfg' to '/home/pi/.attract/emu                                                                                        lators/'
Copying: '/usr/local/share/attract/emulators/snes9x.cfg' to '/home/pi/.attract/e                                                                                        mulators/'
 - Constructed 1 filters in 0 ms (1 comparisons)
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Segmentation fault

**Comment by progets** [comment]
I still haven't been able to get the AM to run when compiling ffmpeg first.

I think the latest AM changes might have broken the AM compile for people that use the pre-built AV modules (which would include RetroPie Setup users).

Here's the output I see if I try to compile AM using the pre-built AV modules (instead of compiling ffmpeg).

pi@retropie:~/develop/attract $ make USE_GLES=1
flags: -Wl,--export-dynamic -I/usr/include/freetype2  -DDATA_PATH=\"/usr/local/s                                                                                        hare/attract/\" -O2 -DNDEBUG -I/opt/vc/include -L/opt/vc/lib -Iextlibs/miniz -Ie                                                                                        xtlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/usr/in                                                                                        clude/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf                                                                                          -DUSE_GLES -DUSE_FONTCONFIG -DUSE_AVRESAMPLE
fatal: No names found, cannot describe anything.
mkdir -p obj
Compiling obj/fe_base.o...
In file included from /usr/include/c++/4.9/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/image.h:14,
                 from extlibs/gameswf/gameswf/gameswf.h:21,
                 from src/fe_base.cpp:34:
/usr/include/c++/4.9/backward/backward_warning.h:32:2: warning: #warning This fi                                                                                        le includes at least one deprecated or antiquated header which may be removed wi                                                                                        thout further notice at a future date. Please use a non-deprecated interface wit                                                                                        h equivalent functionality instead. For a listing of replacement headers and int                                                                                        erfaces, consult the file backward_warning.h. To disable this warning use -Wno-d                                                                                        eprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/fe_util.o...
Compiling obj/fe_util_sq.o...
Compiling obj/fe_cmdline.o...
Compiling obj/fe_info.o...
Compiling obj/fe_input.o...
Compiling obj/fe_romlist.o...
Compiling obj/fe_settings.o...
Compiling obj/scraper_xml.o...
Compiling obj/scraper_general.o...
Compiling obj/scraper_net.o...
Compiling obj/fe_config.o...
Compiling obj/fe_presentable.o...
Compiling obj/fe_present.o...
Compiling obj/sprite.o...
Compiling obj/fe_image.o...
Compiling obj/fe_sound.o...
Compiling obj/fe_shader.o...
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, flo                                                                                        at)':
src/fe_shader.cpp:84:34: warning: 'void sf::Shader::setParameter(const string&,                                                                                         float)' is deprecated (declared at /usr/local/include/SFML/Graphics/Shader.hpp:5                                                                                        54) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x );
                                  ^
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, flo                                                                                        at, float)':
src/fe_shader.cpp:93:37: warning: 'void sf::Shader::setParameter(const string&,                                                                                         float, float)' is deprecated (declared at /usr/local/include/SFML/Graphics/Shade                                                                                        r.hpp:562) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y );
                                     ^
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, flo                                                                                        at, float, float)':
src/fe_shader.cpp:102:40: warning: 'void sf::Shader::setParameter(const string&,                                                                                         float, float, float)' is deprecated (declared at /usr/local/include/SFML/Graphi                                                                                        cs/Shader.hpp:570) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z );
                                        ^
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, flo                                                                                        at, float, float, float)':
src/fe_shader.cpp:111:43: warning: 'void sf::Shader::setParameter(const string&,                                                                                         float, float, float, float)' is deprecated (declared at /usr/local/include/SFML                                                                                        /Graphics/Shader.hpp:578) [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z, w );
                                           ^
src/fe_shader.cpp: In member function 'void FeShader::set_texture_param(const ch                                                                                        ar*)':
src/fe_shader.cpp:120:59: warning: 'void sf::Shader::setParameter(const string&,                                                                                         sf::Shader::CurrentTextureType)' is deprecated (declared at /usr/local/include/                                                                                        SFML/Graphics/Shader.hpp:626) [-Wdeprecated-declarations]
   m_shader.setParameter( name, sf::Shader::CurrentTexture );
                                                           ^
src/fe_shader.cpp: In member function 'void FeShader::set_texture_param(const ch                                                                                        ar*, FeImage*)':
src/fe_shader.cpp:133:42: warning: 'void sf::Shader::setParameter(const string&,                                                                                         const sf::Texture&)' is deprecated (declared at /usr/local/include/SFML/Graphic                                                                                        s/Shader.hpp:618) [-Wdeprecated-declarations]
    m_shader.setParameter( name, *texture );
                                          ^
Compiling obj/fe_overlay.o...
src/fe_overlay.cpp: In member function 'bool FeOverlay::edit_loop(std::vector<sf                                                                                        ::Drawable*>, std::basic_string<unsigned int>&, FeTextPrimative*)':
src/fe_overlay.cpp:1575:34: warning: 'void sf::Text::setColor(const sf::Color&)'                                                                                         is deprecated (declared at /usr/local/include/SFML/Graphics/Text.hpp:177) [-Wde                                                                                        precated-declarations]
  cursor.setColor( tp->getColor() );
                                  ^
Compiling obj/fe_window.o...
Compiling obj/tp.o...
src/tp.cpp: In member function 'void FeTextPrimative::setColor(const sf::Color&)                                                                                        ':
src/tp.cpp:71:26: warning: 'void sf::Text::setColor(const sf::Color&)' is deprec                                                                                        ated (declared at /usr/local/include/SFML/Graphics/Text.hpp:177) [-Wdeprecated-d                                                                                        eclarations]
   m_texts[i].setColor( c );
                          ^
src/tp.cpp: In member function 'const sf::Color& FeTextPrimative::getColor() con                                                                                        st':
src/tp.cpp:76:29: warning: 'const sf::Color& sf::Text::getColor() const' is depr                                                                                        ecated (declared at /usr/local/include/SFML/Graphics/Text.hpp:285) [-Wdeprecated                                                                                        -declarations]
  return m_texts[0].getColor();
                             ^
Compiling obj/fe_text.o...
Compiling obj/fe_listbox.o...
Compiling obj/fe_vm.o...
Compiling obj/zip.o...
Compiling obj/main.o...
src/main.cpp: In function 'int main(int, char**)':
src/main.cpp:561:44: warning: 'sf::Image sf::RenderWindow::capture() const' is d                                                                                        eprecated (declared at /usr/local/include/SFML/Graphics/RenderWindow.hpp:158) [-                                                                                        Wdeprecated-declarations]
       sf::Image sshot_img = window.capture();
                                            ^
Compiling obj/fe_net.o...
Compiling obj/swf.o...
In file included from /usr/include/c++/4.9/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/tu_file.h:18,
                 from src/swf.cpp:26:
/usr/include/c++/4.9/backward/backward_warning.h:32:2: warning: #warning This fi                                                                                        le includes at least one deprecated or antiquated header which may be removed wi                                                                                        thout further notice at a future date. Please use a non-deprecated interface wit                                                                                        h equivalent functionality instead. For a listing of replacement headers and int                                                                                        erfaces, consult the file backward_warning.h. To disable this warning use -Wno-d                                                                                        eprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/media.o...
src/media.cpp: In member function 'bool FeMedia::openFromArchive(const string&,                                                                                         const string&, sf::Texture*)':
src/media.cpp:973:6: error: 'AV_INPUT_BUFFER_PADDING_SIZE' was not declared in t                                                                                        his scope
    + AV_INPUT_BUFFER_PADDING_SIZE );
      ^
src/media.cpp: In member function 'bool FeMedia::internal_open(sf::Texture*)':
src/media.cpp:1033:8: error: 'AV_INPUT_BUFFER_PADDING_SIZE' was not declared in                                                                                         this scope
      + AV_INPUT_BUFFER_PADDING_SIZE
        ^
Makefile:438: recipe for target 'obj/media.o' failed
make: *** [obj/media.o] Error 1
pi@retropie:~/develop/attract $

**Comment by infraredgr** [comment]
I have the same message when i try to run attract (compiled after ffmpeg manually)

pi@raspberrypi:~/develop/attract $ ./attract
Attract-Mode v2.3.0 (Linux, SFML 2.4 +FontConfig +GLES +SWF)
avcodec 58.3.105 / avformat 58.2.102 / swscale 5.0.101 / swresample 3.0.101

Config: /home/pi/.attract/attract.cfg

*** Initializing display: 'Attract Mode Setup'
 - Loaded master romlist 'Attract Mode Setup' in 1 ms (21 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (42 comparisons)
Segmentation fault

**Comment by FatalPunisher88** [comment]
i cannot get this working either way compiling it myself or through experimental packages' get thrown the same errors above.i did get the pulse error to stop by installing pulse audio with
sudo apt-get install pulseaudio
and starting it with 
pulseaudio --start
but I'm not even sure that was what I'm meant to do.at the moment i am trying everything to get this running on my build.i do not want to use pemade builds with it already installed.

**Comment by psyke83** [comment]
I'm curious re: https://github.com/mickelson/attract/commit/4b93a5276fae4b6cdd00d222d9d5b4ba5e02af07

This has broken the build for me on jessie. As far as I can see, the latest package for jessie is libavcodec-dev 6:11.11-1~deb8u1+rpi1, and that has FF_INPUT_BUFFER_PADDING_SIZE defined in avcodec.h, not AV_INPUT_BUFFER_PADDING_SIZE. Are you using a third-party repository or am I missing something?

**Comment by mickelson** [comment]
ok I hope the compile issue is fixed now. If AV_INPUT_BUFFER_PADDING_SIZE is not defined it gets defined to whatever FF_INPUT_BUFFER_PADDING_SIZE is.
AV_INPUT_BUFFER_PADDING_SIZE is being used in recent versions of FFmpeg and libav.  the FF_ version is the old deprecated version, and it appears that RetroPie's default avcodec is old enough to only include the FF_ one

I will still have to look into the seg fault that has been reported in this issue.  So far I've built the most recent ffmpeg and attract-mode on my RPi3 and I am unable to reproduce it.

**Comment by psyke83** [comment]
Building is fixed now - thanks!

Slightly OT, but I've sent two PRs so that your application will use the correct vendor library name (which is only optional on jessie, but is mandatory on stretch, as they removed the old vendor library names):

https://github.com/mickelson/attract/pull/387
https://github.com/mickelson/sfml-pi/pull/7

There's also a [PR](https://github.com/RetroPie/RetroPie-Setup/pull/2213) pending for RetroPie that can be merged if you're happy with the above PRs. I can confirm that both jessie and stretch will build and run correctly when the above three PRs are applied (for a build via RetroPie's script).

**Comment by progets** [comment]
I see new commits for SFML, AM and RetroPie. I can also see that the RetroPie Setup Menu install of AM is fixed. I'm still having seg fault issues when I compile AM myself. I'm thinking that it's something I'm doing wrong when I'm compiling some piece even though there aren't any serious errors. Here's what I'm doing on a Pi3...

1. Installing using the RetroPie Setup Menu - AM runs and works
- download image from https://github.com/RetroPie/RetroPie-Setup/releases/download/4.3/retropie-4.3-rpi2_rpi3.img.gz
- sudo bash ~/RetroPie-Setup/retropie_setup.sh (and upgrade everything)
- install AM from RetroPie Setup Menu

2. Installing compiling SFML, FFMPEG & AM - All compile but AM gets seg fault
- download image from https://github.com/RetroPie/RetroPie-Setup/releases/download/4.3/retropie-4.3-rpi2_rpi3.img.gz
- sudo bash ~/RetroPie-Setup/retropie_setup.sh (and upgrade everything)
`cd ~
mkdir develop

sudo apt-get install cmake libflac-dev libogg-dev libvorbis-dev libopenal-dev libfreetype6-dev libudev-dev libjpeg-dev libudev-dev libfontconfig1-dev

cd ~/develop
git clone --depth 1 https://github.com/mickelson/sfml-pi sfml-pi
mkdir sfml-pi/build;cd sfml-pi/build
cmake .. -DSFML_RPI=1 -DEGL_INCLUDE_DIR=/opt/vc/include -DEGL_LIBRARY=/opt/vc/lib/libbrcmEGL.so -DGLES_INCLUDE_DIR=/opt/vc/include -DGLES_LIBRARY=/opt/vc/lib/libbrcmGLESv2.so
sudo make install
sudo ldconfig

cd ~/develop
git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git
cd ffmpeg
./configure --enable-mmal --disable-debug --enable-shared
make
sudo make install
sudo ldconfig

cd ~/develop
git clone --depth 1 https://github.com/mickelson/attract attract
cd attract
make USE_GLES=1
sudo make install
`

3. Installing compiling SFML & AM with pre-build AV modules - SFML & AM compile but AM gets seg fault
- download image from https://github.com/RetroPie/RetroPie-Setup/releases/download/4.3/retropie-4.3-rpi2_rpi3.img.gz
- sudo bash ~/RetroPie-Setup/retropie_setup.sh (and upgrade everything)
`cd ~
mkdir develop

sudo apt-get install cmake libflac-dev libogg-dev libvorbis-dev libopenal-dev libfreetype6-dev libudev-dev libjpeg-dev libudev-dev libfontconfig1-dev

cd ~/develop
git clone --depth 1 https://github.com/mickelson/sfml-pi sfml-pi
mkdir sfml-pi/build;cd sfml-pi/build
cmake .. -DSFML_RPI=1 -DEGL_INCLUDE_DIR=/opt/vc/include -DEGL_LIBRARY=/opt/vc/lib/libbrcmEGL.so -DGLES_INCLUDE_DIR=/opt/vc/include -DGLES_LIBRARY=/opt/vc/lib/libbrcmGLESv2.so
sudo make install
sudo ldconfig

sudo apt-get install libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavresample-dev

cd ~/develop
git clone --depth 1 https://github.com/mickelson/attract attract
cd attract
make USE_GLES=1
sudo make install
`
Where am I going wrong?

**Comment by progets** [comment]
@mickelson - I saw your post of the forum and it's what I needed. Changing "sudo make install" to "sudo make install USE_GLES=1" when compiling AM fixed the problem. I updated the Pi FAQ and Wiki to let others know.

**Comment by Northguy** [comment]
Hi... I ran into the same issue by pushing the update button from within Attract mode menu on my Raspberry Pi. 

I tried rebuilding from the command prompt according to the Wiki. This works and results in a 'clean' install of attract mode, but this ruined my config settings. I ended up installing a complete new IMG. 

Where do I need to change what, to get updating from inside the Attract Mode menu itself working?

**Comment by bobblepouppy** [comment]
Hi, I tried the update "sudo make install USE_GLES=1" and i still have the segmentation fault.
Somebody know how to get a retropie 4.3 + attract mode clean image?

**Comment by progets** [comment]
@Northguy - There is no update option inside Attract-Mode. That's some script that someone wrote. Ask the creator of your image for help.

@Bobblepouppy - Follow all the step in the Raspberry Pi FAQ on the forum. You need the latest firmware and SFML for everything to work, not just the latest Attract-Mode.

@Everyone else - This problem has been resolved. If you have questions or problems post them on the Attract-Mode forum for help.
